### ISSUE TITLE
Check the filling of the heap logic and the colouring algorithm

### ISSUE THREAD

**Issue by gfmoore** [gfmoore/ESCI-JS#21] opened 2020-07-03 14:54 UTC
I think there is still a slight bias to the right in the heap filling and I want to get to the root of the reason why some red means fall inside the +/- moe bars when the sigma is known. So I'll review the code. :)

**Comment by gfmoore** [comment] 2020-07-06 14:12
Okay, so firstly let me explain what I'm trying to do here.
The width of the viewable area in pixels is given by xmax. (for a narrow window it could be in the order of 500 pixels say).
The width of a mean is 8 pixels. So the number of "buckets I need, each a mean wide, is 500/8 = 62.5. Of course I need a whole number so I round. so 63 buckets. Now I also want to ensure that the centre bucket is on 50. So I need an odd number of buckets. _If the number of buckets is even I subtract one_. (I missed this subtlety which is why for a narrow window it looked a little forced to the right.)

So then for each bucket the min value is the bucket index * 100/no of buckets. 
so for bucket 0 the min edge is 0 and the max edge is 1.5873...   In other words the class interval
for bucket 1 the min edge is 1.5873 and the max edge is 3.1746...

(The class width is 1.5873)

Now if I have a X (my xbar) of 50 it should go in bucket 50/100 * 63 = 31.5 so floor (truncate) and get bucket 31 (Remember the first bucket is bucket 0)

If I have an X of  40 it will go in 40/1.5873 = 25.2000...  which is truncated to 25.

This is okay I think.

Now suppose the popn MoE is 10. Then the mean - MoE is 40 so this is bucket 25, the plus minus MoE bars
The class interval though is 39.6825  to 41.2698

So if I have a MoE that misses then if the X of that was 39.9 it goes in bucket 25 and is coloured red.
If the MoE doesn't miss, then if the X was 40.1 it still goes in bucket 25 and is coloured green.

So we get reds and greens in the same bar.

**Any ideas if I can solve this conundrum?**

I could force means that miss into the bucket before for this edge case, but I think we will get a strange effect.


I hope I've explained this okay. There are some issues that I cannot get my head around to do with whether I should round, ceil (force up) or floor (force down).

For the number of buckets I have rounded and if even gone down by 1. (Not really sure why?)

For the index into which bucket I have floor'd because bucket 0 is the start bucket.

**Comment by gdcumming** [comment] 2020-07-07 04:03
I commented earlier that by taking large samples with small sigma--giving a narrow heap--I can see the issue you raise.

I've said before that it's natural to expect that when a bin overlaps a MoE line, then the column of means in the heap that straddle that line will include a mix of red and green, when sigma known. The proportion of green should, roughly, match the proportion of that bin width that lies inside the MoE line. Very roughly match, that's fine.

I've played around some more, including using mu = 51 and 52, sigma = 21, 22, .... It looks like the mu line, and (I think) the +/- MoE lines are displayed at accurate values, i.e. without any tweaking in relation to bin boundaries. That's good.

But, yes, I can see that, at least often, the red means in the RH tail look shifted to the right relative to the +MoE line, the red means in LH tail also shifted right relative to the -MoE line. (Sigma known)

Rather than seeking a slightly different mix of rounding, forcing up a bit, forcing down a bit, would it be better to do more of the displaying in terms of whole bin widths? For example:

xmax/8 = 62.8, say. Round down, choose to use 62 bins, then use display area that is 62 * 8 pixels wide. Adjust the width of the display area a tiny bit to fit this, by shifting the right hand edge inwards a tiny bit. (Typically less than 1mm on the screen, giving a tiny bit of white space on the right.) Horizontal axes are from 0 to 100 across this slightly less wide display area. Then calculate bin left and right hand ends, as you do. Don't worry about 50 having to be in the middle of a bin--landing at a bin boundary would be just as neat. So we can work with an odd or even number of bins. 

On my big screen there are roughly 190 bins, so xmax must be around 1500.

Yes, it's neat having the default mu value of 50 fall either midbin, or at bin boundary. It's fine that other mu values fall at some arbitrary point in a bin width. Ditto for +/- MoE lines.

With the above strategy, if feasible, then judge capture by comparing a sample mean (accurate value) with +/- MoE line values (accurate value) and colouring the mean accordingly should give the proportions I mention above in para 2.

I think!

**Comment by gfmoore** [comment] 2020-07-07 20:13
I commented earlier that by taking large samples with small sigma--giving a narrow heap--I can see the issue you raise.

>> Yes when I'm developing I normally have a narrow window so that I can tweak in the IDE and see the effect in the browser window, plus I use the developer tools option (F12 on a browser) to debug etc. Even though VS Code is good it still isn't integrated enough for this kind of development - I'd have to set up my machine as a full windows server (it already can be, but I haven't really needed to go that extra complexity yet - setting up firewalls ips and other config.) That's why really I should work at a desk and have three 28 inch monitors in front of me. :) (I'm not going to do that ... yet!)

I've said before that it's natural to expect that when a bin overlaps a MoE line, then the column of means in the heap that straddle that line will include a mix of red and green, when sigma known. The proportion of green should, roughly, match the proportion of that bin width that lies inside the MoE line. Very roughly match, that's fine.

>> yes, but I thought you meant when the population is unknown? Technically all misses should lie outside the +/- moe lines when sigma known, yes? It would be nice to get that visual effect.

I've played around some more, including using mu = 51 and 52, sigma = 21, 22, .... It looks like the mu line, and (I think) the +/- MoE lines are displayed at accurate values, i.e. without any tweaking in relation to bin boundaries. That's good.

>> yes they are mathematical to the nearest pixel at any rate

But, yes, I can see that, at least often, the red means in the RH tail look shifted to the right relative to the +MoE line, the red means in LH tail also shifted right relative to the -MoE line. (Sigma known)

>> I've hopefully changed that now by having a bin such that the 50 line goes through it. I don't know about other mean values, I suspect that they could cover the whole class interval width of the bin! Is that going to be a major problem? I hope not :)

Perhaps your next set of comments addresses this.

**Comment by gfmoore** [comment] 2020-07-07 20:31
Rather than seeking a slightly different mix of rounding, forcing up a bit, forcing down a bit, would it be better to do more of the displaying in terms of whole bin widths? For example:

>> so I'm not changing at the moment, it was just a thought and something I've previously played with.

xmax/8 = 62.8, say. Round down, choose to use 62 bins, then use display area that is 62 * 8 pixels wide. Adjust the width of the display area a tiny bit to fit this, by shifting the right hand edge inwards a tiny bit. (Typically less than 1mm on the screen, giving a tiny bit of white space on the right.) 

>> I don't really want to start changing the display width of the bottom dropping zone at this stage, the knock on effects on dropping means, moe wings etc could be a bit too much - sorry. If it becomes really necessary then yes I'm going to have to redesign. .

>> okay, but shouldn't the left hand edge of the start bin be pushed in a little (or are we talking the same thing from different perspectives.?)

Horizontal axes are from 0 to 100 across this slightly less wide display area. Then calculate bin left and right hand ends, as you do. Don't worry about 50 having to be in the middle of a bin--landing at a bin boundary would be just as neat. So we can work with an odd or even number of bins.

On my big screen there are roughly 190 bins, so xmax must be around 1500.

Yes, it's neat having the default mu value of 50 fall either midbin, or at bin boundary. It's fine that other mu values fall at some arbitrary point in a bin width. Ditto for +/- MoE lines.

With the above strategy, if feasible, then judge capture by comparing a sample mean (accurate value) with +/- MoE line values (accurate value) and colouring the mean accordingly should give the proportions I mention above in para 2.

>>Nope, I don't think I get this. Sorry. I'm sure you're right, but I see this being a big job at this late stage. 

>> I'm thinking that for the mean to be coloured properly then the +/- MoE lines have to be on a bin boundary. To do that I'd have to calculate where that boundary should be and put 8 pixel wide bins to the left and right. But suppose I start at the minus MoE line, then creating bins to the right might, probably would, cause the left MoE bin ine to be out of sync (and the mean as well), so we are back where we started.

>> The issue is that I am creating a discrete bar chart based on continuous values and mapping to a pixel based display. 
>> Now if we had a continuous display and I scaled everything in proportion as we scaled the display, then fine. Sadly however we have a fixed mean blob size and so fixed bin width size and no matter how we position it something will give?

>> or am I missing a huge point? Very likely, because like Pooh bear, my brain is a little tiny. 

I think!

>> :)

>> Okay how about this, can you live with it as is? If not then we'll set aside much more time and think it through again. 

>> It's good to think it through though.

**Comment by gfmoore** [comment] 2020-07-07 20:40
With the above strategy, if feasible, then judge capture by comparing a sample mean (accurate value) with +/- MoE line values (accurate value) and colouring the mean accordingly should give the proportions I mention above in para 2.

>> The MoE capture is already accurately calculated and stored in the dropping mean. These are then coloured accordingly (and given the rules of CI, Mean Line, capture mean). So I'm not comparing the centre of the bin with the MoE or anything, just in case you thought I might be. Everything is accurate ( to a 14 dp - not that it's that accurate of course - IEEE 754 floating point specification).

**Comment by gdcumming** [comment] 2020-07-10 08:14
0.3.42

I'm much reassured that the following are all recorded and displayed accurately:
mu 
+/-MoE
means
--also that capture and red/green colour of means and CIs is determined by accurate comparisons of CI limit with mu. (For sigma known, we can do comparison of mean with +/- MoE line, but for sigma unknown we need comparison of CI limit with mu. I guess that's what you do?)

All the above is great.

To try to diagnose why we still seem to be getting means in the heap displayed too far to the right, I tried the extreme case of sigma=5, N=100, mu=4 (type in the value). All seems fine. Means in the heap don't seem too far right.

But try the above, but mu=96 and means in the heap seem shifted right, perhaps by about one bin width. Sample slowly and see means drop, then make a leap to the right to get into their assigned column in the heap.

The above two observations suggest that we have a scale factor problem, not a zero error. I.e. need to adjust the bin *width* calculations, not worry about the left hand end, or whether rounding down to a bin boundary is an issue.

Looking back at your second comment above, which explains how you calculate number of bins needed, the bin width, and bin boundaries, I wonder if the problem is rounding 62.5 to 63, and/or subtracting 1 when needed to get an odd number of bins?

I suggest that you try using xmax/8 as the number of bins, *without* any rounding or adjustment, for the purpose of calculating bin width and bin boundaries. Then bin width = 100/62.5=1.600. Sure the rightmost bin may be skinny or part-way off screen, but we don't care exactly what happens way out there. We care that bins are all exactly 8 pixels wide, because that's built into the calcs?

Would that one tweak to the calcs be easy to try? Then try that sampling with the above values, esp. with mu=4 and mu=96, and it should be easy to see whether that fixes the problem. Or possibly some other tweak to bin width so we don't get a scale factor problem that progressively increases from no problem at left hand end to clearly visible problem at right hand end.

**Comment by gfmoore** [comment] 2020-07-10 09:11
I suggest that you try using xmax/8 as the number of bins, without any rounding or adjustment,

>> You can't have a non integer number of bins. There is an **array** for the bins that I use as a frequency count. I've probably over-simplified the design, not anticipating these issues. I'd have to do some major re-design to record exact class widths for  each bin. Uhmmm, will have to think how I can do this, might have to use an array of JavaScript objects rather than a simple array. Leave it with me, but I might be some time! ;)

**Comment by gfmoore** [comment] 2020-07-10 09:14
I see what you mean about the extreme case.

**Comment by gdcumming** [comment] 2020-07-12 00:15
0.3.48

Hmmm, I hoped it would not be that complicated, given what I read into your initial description of how you decide which bin to put a mean into.

I've done a few more observations, probably not adding much. Watch means (no CIs) drop onto the heap, moderately fast sampling. For mu way to the left, see means either drop straight onto a column, or dance a tiny bit L or R. Shifts to L or R seem roughly equally common. Do the same for mu way to the right and see virtually all means drop straight on, or dance a small amount or a larger amount always to the R--up to about one bin width.

On my screen, a tall narrow heap far to the right looks like it needs shifting left about one column width to fit the curve. On a second screen, with different characteristics, same thing but to a smaller extent. In both cases, heap to the far left looks to fit the curve well.

The classification of means as red/green, and assignment of means into the tails of the heap seems accurate (in the long term, about equal numbers of red in L and R tails). That's as we expect, given that you keep accurate values for means, mu, MoE lines.

All of which is consistent with my conclusion that the only issue is calculating which bin a particular mean should be assigned to, and that the assignment is accurate at L end of axis, and progressively less accurate at axis values rising from 0 across to 100 at the R end--where they seem to be out (on my big screen) by about one width.

In other words, we have, as I suggested, a scaling issue, not a zero-positioning issue.

To choose bin, you say:
"Now if I have a X (my xbar) of 50 it should go in bucket 50/100 * 63 = 31.5 so floor (truncate) and get bucket 31 (Remember the first bucket is bucket 0)"

In other words, we calculate which bin we need by counting across from L end in units of bin widths. So it looks like we are using a value for bin width that is too small--so we tend to get a higher bin number than that particular mean should have. And a progressively larger error towards the R end.

I didn't express myself well, sorry. Sure, there needs to be an integral number of bins, 63 in the example. But to find the bin width we should use 62.5 (in your original example) as divisor, noting that that means that the 63rd bin will be a different width, perhaps very skinny. But we don't care exactly what happens (very rarely) way out there at 100 on the R. We do care that the calc we use to assign means to bins is accurate for the first 62 bins at least. Using 1.600 rather than 1.5873 as our value for bin width would be an adjustment in the direction we want, i.e. a change in scale factor.

That's long-winded, sorry. I'm hoping that the change from using 63 to 62.5 as the divisor to calculate bin width might be simple to try, and worth trying. I suspect we're very close to perfect fit...!

**Comment by gfmoore** [comment] 2020-07-12 20:55
Ok so I think I've now followed you. Quite straightforward once I took it slowly and can see what you mean.  Sorry, I'm not really as clever as I thought I was ;) 

As an (elementary) maths teacher I always recognised that individuals have a certain cognitive level they can attain to. Sure it can be increased with training and good teaching, but I knew I never had the mental ability to study maths at a post graduate level. Sometimes I just don't get it. For instance I'm trying to get my head around Bayesian statistics. It's a real struggle for me. I know given enough time I'll get there, but it's hard slog for me. It's the same with music/guitar. I know I'll never be that good at it, well maybe in a thousand years. Some people can just do it...

Anyhow, enough of my misery :) 

Let me know what you think.

Drawing a custom rectangle at the far right of a narrow width is a quick way of getting to that side:)

**Comment by gdcumming** [comment] 2020-07-13 00:51
0.3.55

Banish all misery! Totally unwarranted. No more putting down of the expert Gordon!

This looks good to me. If there is any rightwards bias out toward the 100 end it's tiny, and maybe in my fevered imagination, and no-one else will ever find it.

No, very good indeed, thanks. Can close this issue--I see I can't do that.

**Closed as completed** 2020-07-13 08:22 UTC
